// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./views/404.vue')['default']
    About: typeof import('./views/about/About.vue')['default']
    ActAnalysis: typeof import('./views/activity/ActAnalysis.vue')['default']
    ActForm: typeof import('./views/activity/ActForm.vue')['default']
    ActManager: typeof import('./views/activity/ActManager.vue')['default']
    Bread: typeof import('./components/Bread.vue')['default']
    Content: typeof import('./views/layout/Content.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    HeadNav: typeof import('./views/layout/HeadNav.vue')['default']
    Home: typeof import('./views/home/Home.vue')['default']
    Layout: typeof import('./views/layout/Layout.vue')['default']
    LeftMenu: typeof import('./views/layout/LeftMenu.vue')['default']
    Login: typeof import('./views/login/Login.vue')['default']
    TodoList: typeof import('./views/todolist/TodoList.vue')['default']
    Weather: typeof import('./views/weather/Weather.vue')['default']
  }
}

export { }
